# Generated by Django 2.2.9 on 2020-01-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='Уровни пайщиков')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=20, verbose_name='Тарифы')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='ShareholderRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('dateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('uniqueNumber', models.IntegerField(db_index=True, unique=True, verbose_name='Уникальный номер')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='Слаг')),
                ('following', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments_register.ShareholderRegister', verbose_name='Пригласитель')),
                ('levelUser', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='investments_register.LevelRegister', verbose_name='Уровень')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments_register.Rate', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Пайщика',
                'verbose_name_plural': 'Пайщиков',
            },
        ),
    ]
